// General
export const STATE = 'state';

// Actions
export const CHANGE_BUDGET = 'CHANGE_BUDGET';
export const SAVE_BUDGET = 'SAVE_BUDGET';
export const CLOSE_CHANGE_BUDGET_FORM = 'CLOSE_CHANGE_BUDGET_FORM';

export const FILTER_BY_PRICE = 'OPEN_FILTER_PRICE_FORM';
export const PERFORM_FILTER = 'PERFORM_FILTER';
export const CLOSE_FILTER_PRICE_FORM = 'CLOSE_FILTER_PRICE_FORM';

export const ZOOM_IN_ON_SERVICE = 'ZOOM_IN_ON_SERVICE' ;
export const  ZOOM_OUT_OF_SERVICE = 'ZOOM_OUT_OF_SERVICE';

export const REVIEW_CART = 'REVIEW_CART';
export const CLOSE_CART_REVIEW = 'CLOSE_CART_REVIEW';

export const HIDE_CART_ITEM = 'HIDE_CART_ITEM';
export const SHOW_CART_ITEM = 'SHOW_CART_ITEM';
export const REMOVE_CART_ITEM = 'REMOVE_CART_ITEM';
export const REMOVE_HIDDEN_CART_ITEM = 'REMOVE_HIDDEN_CART_ITEM';
export const ADD_ITEM_TO_CART = 'ADD_ITEM_TO_CART';

export const AMOUNT_OUT_OF_RANGE = 'AMOUNT_OUT_OF_RANGE';
export const AMOUNT_IN_RANGE = 'AMOUNT_IN_RANGE';

export const FETCH_SERVICES = 'FETCH_SERVICES';
export const RECEIVE_SERVICES = 'RECEIVE_SERVICES';
export const START_LOADING_SERVICES = 'START_LOADING_SERVICES';
export const FINISH_LOADING_SERVICES = 'FINISH_LOADING_SERVICES';
export const LOADING_SERVICES_FAILED = 'LOADING_SERVICES_FAILED';

export const FETCH_SERVICE = 'FETCH_SERVICE';
export const RECEIVE_SERVICE = 'RECEIVE_SERVICE';
export const VIEW_SERVICE = 'VIEW_SERVICE';
export const START_LOADING_SERVICE = 'START_LOADING_SERVICE';
export const FINISH_LOADING_SERVICE = 'FINISH_LOADING_SERVICE';
export const LOADING_SERVICE_FAILED = 'LOADING_SERVICE_FAILED';

export const FETCH_CATEGORIES = 'FETCH_CATEGORIES';
export const RECEIVE_CATEGORIES = 'RECEIVE_CATEGORIES';
export const START_LOADING_CATEGORIES = 'START_LOADING_CATEGORIES';
export const FINISH_LOADING_CATEGORIES = 'FINISH_LOADING_CATEGORIES';
export const LOADING_CATEGORIES_FAILED = 'LOADING_CATEGORIES_FAILED';
export const SELECT_CATEGORY = 'SELECT_CATEGORY';